on:
  pull_request:
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: Publish mcpx-py
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: uv publish
        run: uv publish
